### ISSUE TITLE
Wilcox and ANOVO Volcano plots don't seem to render.

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#620]
via @jkanche

**Comment by mvandenburgh** [comment]
Looks like the ANOVA volcano plot not rendering happens when the ANOVA test fails. If ANOVA fails we now catch that and display an error in the ANOVA page (https://github.com/girder/viime/issues/599) but not in the ANOVA volcano plot page. Should be able to parse the response from the ANOVA analysis and display an error message for the volcano plot.


https://viime.org/#/app/pretreatment/dbe03b9d-8007-4508-9de2-a138d7402580/analyze/anova_volcano

**Comment by mvandenburgh** [comment]
I addressed the ANOVA errors in https://github.com/girder/viime/pull/631. For the Wilcoxon plot render error, I suspect this is the cause of the plot not rendering - https://sentry.io/organizations/kitware-data/issues/1822253993/?project=1814175&query=is%3Aunresolved
Unfortunately I'm still unable to reproduce the Wilcoxon error locally, even using the exact same dataset as the one in that sentry error. 

I can modify the R code to catch errors in the wilcoxon test like I did for ANOVA, but in that case those errors were completely normal in the sense that ANOVA tests can sometimes fail mathematically. It seems based on the sentry error that the wilcoxon test might be failing because of a programming error, which should be fixed instead of being displayed as a user error.

**Comment by waxlamp** [comment]
> I can modify the R code to catch errors in the wilcoxon test like I did for ANOVA, but in that case those errors were completely normal in the sense that ANOVA tests can sometimes fail mathematically. It seems based on the sentry error that the wilcoxon test might be failing because of a programming error, which should be fixed instead of being displayed as a user error.

We can at least display this kind of error as a *server* error, and that gives the user closure (rather than leaving them wondering what's going on).

I'll ask Lilian to look into programming errors in the Wilcoxon test code.

**Comment by waxlamp** [comment]
@jkanche, I believe this is now fixed. Please take a look and re-open this issue if you find lingering problems. Thanks!

**Comment by joannawolthuis** [comment]
Hi! I didn't submit this one, but I still can't see anything upon running the ANOVA/Wilcox. volcano plots, I assume there should be some kind of error/no hits found message? But in my case I did have hits in the ANOVA/Wilcox.. 😮 
![image](https://user-images.githubusercontent.com/16805477/92455892-85dca200-f1c2-11ea-8869-f7c873a42c1f.png)

**Comment by waxlamp** [comment]
@joannawolthuis, could you show me what your Cleanup Table looks like for this dataset?

**Comment by joannawolthuis** [comment]
@waxlamp Hi, thanks for your response!
I think it fixed itself - once I went back to the Clean Up table to de-select and re-select the metadata column (for the boxplots split by group not loading, other issue), both volcano plots loaded. Seems it's a connected issue - and since you're already working on that you can close this if you want :)
